# -*- coding: utf-8 -*-
"""auth

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp4C-RJWOBEO0XSGhws1aTOmtjPW1ChD
"""

# auth.py
import streamlit as st
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import Flow
import googleapiclient.discovery
import gspread
import os
import json

# Define necessary scopes
SCOPES = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive',
    'openid', # Basic profile info
    'https://www.googleapis.com/auth/userinfo.email', # Email address
    'https://www.googleapis.com/auth/userinfo.profile', # Name, picture
]

# --- Load Credentials from Secrets ---
try:
    GOOGLE_CLIENT_ID = st.secrets["GOOGLE_CLIENT_ID"]
    GOOGLE_CLIENT_SECRET = st.secrets["GOOGLE_CLIENT_SECRET"]
    GOOGLE_REDIRECT_URI = st.secrets["GOOGLE_REDIRECT_URI"]
except KeyError as e:
    st.error(f"Missing Google OAuth secret: {e}. Please configure .streamlit/secrets.toml")
    st.stop()

# Client config dictionary
client_config = {
    "web": {
        "client_id": GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "redirect_uris": [GOOGLE_REDIRECT_URI],
        "javascript_origins": ["http://localhost:8501"] # Adjust if needed
    }
}

def get_google_flow():
    """Initializes the Google OAuth Flow."""
    return Flow.from_client_config(
        client_config=client_config,
        scopes=SCOPES,
        redirect_uri=GOOGLE_REDIRECT_URI
    )

def get_auth_url():
    """Generates the Google Authentication URL."""
    flow = get_google_flow()
    authorization_url, state = flow.authorization_url(
        access_type='offline',
        include_granted_scopes='true',
        prompt='consent' # Force consent screen for refresh token
    )
    # Store state in session to verify callback
    st.session_state['oauth_state'] = state
    return authorization_url

def exchange_code_for_credentials(code, state):
    """Exchanges the authorization code for credentials."""
    # Verify state to prevent CSRF attacks
    if 'oauth_state' not in st.session_state or st.session_state['oauth_state'] != state:
        st.error("Authentication failed: State mismatch.")
        return None
    try:
        flow = get_google_flow()
        flow.fetch_token(code=code)
        credentials = flow.credentials
        # Store credentials securely in session state
        st.session_state['google_credentials'] = credentials_to_dict(credentials)
        return credentials
    except Exception as e:
        st.error(f"Failed to exchange code for token: {e}")
        return None

def credentials_to_dict(credentials):
    """Converts Google Credentials object to a serializable dictionary."""
    return {
        'token': credentials.token,
        'refresh_token': credentials.refresh_token,
        'token_uri': credentials.token_uri,
        'client_id': credentials.client_id,
        'client_secret': credentials.client_secret,
        'scopes': credentials.scopes,
        'id_token': getattr(credentials, 'id_token', None) # Include id_token if present
    }

def credentials_from_dict(credentials_dict):
    """Creates Google Credentials object from a dictionary."""
    if not credentials_dict:
        return None
    return Credentials(**credentials_dict)

def get_user_info(credentials):
    """Fetches user info (email, name, picture) using credentials."""
    try:
        userinfo_service = googleapiclient.discovery.build(
            'oauth2', 'v2', credentials=credentials)
        user_info = userinfo_service.userinfo().get().execute()
        st.session_state['user_info'] = user_info # Store user info
        return user_info
    except Exception as e:
        st.error(f"Failed to fetch user info: {e}")
        return None

# --- Functions to initialize API clients ---
# Use caching to avoid re-initializing clients on every script rerun

@st.cache_resource
def get_gspread_client(_credentials_dict):
    """Initializes and returns an authenticated gspread client."""
    credentials = credentials_from_dict(_credentials_dict)
    if not credentials or not credentials.valid:
        st.warning("Invalid or missing Google credentials for gspread.")
        return None
    try:
        gc = gspread.authorize(credentials)
        return gc
    except Exception as e:
        st.error(f"Failed to initialize gspread client: {e}")
        return None

@st.cache_resource
def get_drive_service(_credentials_dict):
    """Initializes and returns an authenticated Google Drive service client."""
    credentials = credentials_from_dict(_credentials_dict)
    if not credentials or not credentials.valid:
        st.warning("Invalid or missing Google credentials for Drive.")
        return None
    try:
        drive_service = googleapiclient.discovery.build('drive', 'v3', credentials=credentials)
        return drive_service
    except Exception as e:
        st.error(f"Failed to initialize Drive service: {e}")
        return None