# -*- coding: utf-8 -*-
"""backend

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOLqJagKEXBPSk7oSHvcaay0uqC17zKa
"""

# backend.py
# Contains the core logic adapted from the Colab script.
# Functions are modified to accept clients/keys and work with Streamlit state/caching.

import streamlit as st
import os
import json
import base64
import pandas as pd
import requests
import time
from openai import OpenAI
from gspread_dataframe import set_with_dataframe, get_as_dataframe

# --- Load API Keys ---
# Note: OpenAI client is initialized globally here for simplicity,
# but could be passed around if preferred.
OPENAI_API_KEY = st.secrets.get("OPENAI_API_KEY")
OPENWEATHER_API_KEY = st.secrets.get("OPENWEATHER_API_KEY")
client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

# --- Load Folder IDs ---
ITEMS_WOMEN_FOLDER_ID = st.secrets.get("ITEMS_WOMEN_FOLDER_ID")
ITEMS_MEN_FOLDER_ID = st.secrets.get("ITEMS_MEN_FOLDER_ID")
CATALOG_FOLDER_ID = st.secrets.get("CATALOG_FOLDER_ID")
# Base path might need adjustment depending on how Drive is accessed via API vs mounted Colab path
# For API access, we usually don't need a local-like path.
# INVENTORY_BASE_PATH = st.secrets.get("INVENTORY_BASE_PATH", "/content/drive/MyDrive/Wadrobe/")


# --- Google Drive/Sheets Helpers (Adapted) ---

# Use caching for functions that don't change often based on inputs
@st.cache_data(ttl=600) # Cache for 10 minutes
def check_gsheet_id(_drive_service, folder_id, sheet_name):
    """Finds the Google Sheet ID."""
    if not _drive_service: return None, False
    try:
        query = f"'{folder_id}' in parents and mimeType='application/vnd.google-apps.spreadsheet' and name='{sheet_name}' and trashed=false"
        results = _drive_service.files().list(q=query, fields="files(id, name)").execute()
        files = results.get("files", [])
        if files:
            return files[0]["id"], True
        return None, False
    except Exception as e:
        st.error(f"Error checking GSheet ID for '{sheet_name}': {e}")
        return None, False

# Cache the data read from the sheet
@st.cache_data(ttl=600) # Cache for 10 minutes
def read_gsheet(_gc, _drive_service, folder_id, sheet_name):
    """Reads Google Sheet into DataFrame."""
    if not _gc or not _drive_service: return None
    sheet_id, is_available = check_gsheet_id(_drive_service, folder_id, sheet_name)
    if is_available:
        try:
            spreadsheet = _gc.open_by_key(sheet_id)
            worksheet = spreadsheet.sheet1
            df = get_as_dataframe(worksheet, evaluate_formulas=True, dtype=str, header=0)
            df.dropna(axis=0, how='all', inplace=True)
            df.dropna(axis=1, how='all', inplace=True)
            # Convert JSON string columns back to lists/dicts after reading
            list_cols = ['color', 'weather', 'occasion']
            for col in list_cols:
                 if col in df.columns:
                      df[col] = df[col].apply(lambda x: json.loads(x) if isinstance(x, str) and x.startswith('[') else ([] if pd.isna(x) else x))
            if 'description' in df.columns:
                 df['description'] = df['description'].apply(lambda x: json.loads(x) if isinstance(x, str) and x.startswith('{') else ({} if pd.isna(x) else x))

            return df
        except Exception as e:
            st.error(f"Error reading GSheet '{sheet_name}': {e}")
            return None
    return None # Return None if sheet not found

# Don't cache functions that modify external state (like creating/updating sheets)
def create_gsheet(_gc, _drive_service, folder_id, sheet_name, sheet_data):
    """Creates Google Sheet."""
    if not _gc or not _drive_service or sheet_data.empty: return False
    try:
        spreadsheet = _gc.create(sheet_name)
        _drive_service.files().update(
            fileId=spreadsheet.id, addParents=folder_id, removeParents='root', fields='id, parents'
        ).execute()
        worksheet = spreadsheet.sheet1
        # Convert lists/dicts back to JSON strings before writing
        df_to_write = sheet_data.copy()
        list_cols = ['color', 'weather', 'occasion']
        for col in list_cols:
            if col in df_to_write.columns:
                df_to_write[col] = df_to_write[col].apply(json.dumps)
        if 'description' in df_to_write.columns and isinstance(df_to_write['description'].iloc[0], dict):
             df_to_write['description'] = df_to_write['description'].apply(json.dumps)

        set_with_dataframe(worksheet, df_to_write, include_index=False)
        st.cache_data.clear() # Clear cache after modifying sheet
        return True
    except Exception as e:
        st.error(f"Error creating GSheet '{sheet_name}': {e}")
        return False

def update_gsheet(_gc, _drive_service, folder_id, sheet_name, new_data):
    """Updates Google Sheet."""
    if not _gc or not _drive_service or new_data.empty: return False
    sheet_id, is_available = check_gsheet_id(_drive_service, folder_id, sheet_name)
    if is_available:
        try:
            existing_data = read_gsheet(_gc, _drive_service, folder_id, sheet_name) # Read existing data (will be cached)
            if existing_data is None: return False # Read failed
            updated_data = pd.concat([existing_data, new_data], ignore_index=True) if not existing_data.empty else new_data
            # Optional: Drop duplicates
            updated_data.drop_duplicates(subset=['file name'], keep='last', inplace=True)

            spreadsheet = _gc.open_by_key(sheet_id)
            worksheet = spreadsheet.sheet1
            worksheet.clear()
            # Convert lists/dicts back to JSON strings before writing
            df_to_write = updated_data.copy()
            list_cols = ['color', 'weather', 'occasion']
            for col in list_cols:
                 if col in df_to_write.columns:
                      df_to_write[col] = df_to_write[col].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)
            if 'description' in df_to_write.columns and isinstance(df_to_write['description'].iloc[0], dict):
                 df_to_write['description'] = df_to_write['description'].apply(lambda x: json.dumps(x) if isinstance(x, dict) else x)

            set_with_dataframe(worksheet, df_to_write, include_index=False)
            st.cache_data.clear() # Clear cache after modifying sheet
            return True
        except Exception as e:
            st.error(f"Error updating GSheet '{sheet_name}': {e}")
            return False
    return False # Sheet not available

@st.cache_data(ttl=600)
def get_gsheet_last_modified(_drive_service, sheet_folder_id, sheet_name):
    """Gets GSheet last modified time."""
    if not _drive_service: return None
    sheet_id, is_available = check_gsheet_id(_drive_service, sheet_folder_id, sheet_name)
    if is_available:
        try:
            file_metadata = _drive_service.files().get(fileId=sheet_id, fields='id, name, modifiedTime').execute()
            return file_metadata.get('modifiedTime')
        except Exception as e:
            st.error(f"Error getting last modified time for sheet ID '{sheet_id}': {e}")
            return None
    return None

@st.cache_data(ttl=300) # Cache file list for 5 mins
def get_files_in_drive_folder(_drive_service, folder_id, after_timestamp=None):
    """Lists files in Drive folder."""
    if not _drive_service: return []
    file_details = []
    try:
        query = f"'{folder_id}' in parents and trashed=false"
        if after_timestamp: query += f" and createdTime > '{after_timestamp}'"
        page_token = None
        while True:
            results = _drive_service.files().list(
                q=query, pageSize=100, fields="nextPageToken, files(id, name, createdTime, mimeType, webViewLink, thumbnailLink)", # Get more fields
                pageToken=page_token
            ).execute()
            files = results.get("files", [])
            for file in files:
                 # Filter out non-image files if necessary based on mimeType
                 if file.get('mimeType', '').startswith('image/'):
                      file_details.append({
                           'id': file['id'],
                           'name': file['name'],
                           'createdTime': file.get('createdTime'),
                           'webViewLink': file.get('webViewLink'), # Link to view in Drive
                           'thumbnailLink': file.get('thumbnailLink') # Small preview link
                      })
            page_token = results.get('nextPageToken', None)
            if page_token is None: break
        return file_details
    except Exception as e:
        st.error(f"Error listing files in Drive folder '{folder_id}': {e}")
        return []

# --- Agent 1: Image Analysis & Inventory Update (Adapted) ---

def encode_image(image_bytes):
    """Encodes image bytes into base64."""
    try:
        return base64.b64encode(image_bytes).decode("utf-8")
    except Exception as e:
        st.error(f"Error encoding image bytes: {e}")
        return None

# Cache the description to avoid re-analyzing the same image bytes
# Note: Caching based on bytes might consume memory if images are large.
# Consider caching based on a hash of the bytes if memory is a concern.
@st.cache_data(max_entries=200) # Cache results for up to 200 images
def get_description_json_cached(image_bytes_hash, image_base64):
     """Wrapper for caching get_description_json."""
     # The hash isn't used directly here but makes the cache key unique per image content
     return get_description_json(image_base64)


def get_description_json(image_base64):
    """Sends image to OpenAI for description."""
    if not client: return {"error": "OpenAI client not available"}
    if not image_base64: return {"error": "Invalid image data"}
    # Prompts remain the same as in Colab version...
    system_prompt_image = "You are an AI assistant specialized in analyzing clothing items..." # Keep full prompt
    user_prompt_image = [
        {"type": "text", "text": """Analyze the clothing item... (Keep full prompt)"""},
        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{image_base64}"}},
    ]
    try:
        response = client.chat.completions.create(
            model="gpt-4o", messages=[{"role": "system", "content": system_prompt_image}, {"role": "user", "content": user_prompt_image}],
            max_tokens=500, temperature=0.2
        )
        content = response.choices[0].message.content
        if content.startswith("```json"): content = content[7:]
        if content.endswith("```"): content = content[:-3]
        response_json = json.loads(content.strip())
        if response_json.get("type", "").lower() == "non-clothing": return None
        return response_json
    except Exception as e:
        st.error(f"Error getting image description from OpenAI: {e}")
        return {"error": f"OpenAI API call failed: {e}"}

def process_uploaded_files(uploaded_files):
    """Processes files uploaded via Streamlit."""
    inventory_data = []
    if not uploaded_files: return pd.DataFrame()

    for uploaded_file in uploaded_files:
        st.write(f"Processing {uploaded_file.name}...")
        image_bytes = uploaded_file.getvalue()
        image_base64 = encode_image(image_bytes)
        if not image_base64: continue

        # Use caching based on bytes hash
        img_hash = hash(image_bytes) # Simple hash for cache key
        image_description = get_description_json_cached(img_hash, image_base64)

        if image_description is None: continue # Skip non-clothing
        if "error" in image_description:
            st.warning(f"Could not get description for {uploaded_file.name}: {image_description['error']}")
            continue

        item_data = {
            "file name": uploaded_file.name, # Use uploaded file name
            "description": image_description, # Store as dict directly now
            "category": image_description.get('type', 'N/A'),
            "sub-category": image_description.get('subtype', 'N/A'),
            "color": image_description.get('color', []), # Store as list
            "pattern": image_description.get('pattern', ''),
            "weather": image_description.get('weather', []), # Store as list
            "occasion": image_description.get('occasion', []) # Store as list
        }
        inventory_data.append(item_data)

    return pd.DataFrame(inventory_data)


# --- Agent: Query Relevancy Check (Adapted) ---
@st.cache_data
def is_query_relevant(user_query):
    """Checks query relevancy using LLM."""
    if not client: return True # Default to relevant if no client
    system_prompt_relevancy = "..." # Same prompt as before
    try:
        response = client.chat.completions.create(
            model="gpt-3.5-turbo", messages=[{"role": "system", "content": system_prompt_relevancy}, {"role": "user", "content": user_query}],
            max_tokens=5, temperature=0.0
        )
        return response.choices[0].message.content.strip().upper() == "YES"
    except Exception as e:
        st.warning(f"Relevancy check failed: {e}")
        return True # Default true on error

# --- Agent: Weather Fetcher (Adapted) ---
class WeatherAgent:
    BASE_URL = "https://api.openweathermap.org/data/2.5/weather"
    def __init__(self, zip_code, api_key):
        if not api_key: raise ValueError("OpenWeatherMap API key required.")
        self.zip_code = zip_code
        self.api_key = api_key

    # Cache weather data for a short time
    @st.cache_data(ttl=900) # Cache for 15 minutes
    def get_weather(_self): # Use _self because st.cache_data doesn't handle instance methods well directly
        """Fetches current weather."""
        params = {'zip': f"{_self.zip_code},us", 'appid': _self.api_key, 'units': 'metric'}
        try:
            response = requests.get(_self.BASE_URL, params=params, timeout=10)
            response.raise_for_status()
            data = response.json()
            # Validation... (same as before)
            temp_celsius = data['main']['temp']
            condition = data['weather'][0]['main'].lower()
            description = data['weather'][0]['description'].lower()
            temp_fahrenheit = (temp_celsius * 9/5) + 32
            return {'temp_celsius': round(temp_celsius, 1), 'temp_fahrenheit': round(temp_fahrenheit, 1), 'condition': condition, 'description': description}
        except Exception as e:
            st.error(f"Weather fetch error: {e}")
            # Return default or raise? Returning default for smoother UI
            return {'temp_celsius': 20, 'temp_fahrenheit': 68, 'condition': 'clear', 'description': 'unknown (fetch error)'}


# --- Agent: Outfit Recommendation & Evaluation (Adapted) ---
class FashionRecommender:
    def __init__(self, inventory_df, weather_data, user_query):
        if not client: raise RuntimeError("OpenAI client not initialized.")
        if inventory_df is None or inventory_df.empty: raise ValueError("Inventory DF missing.")
        # Preprocess inventory DataFrame (parsing lists/dicts if read from sheet)
        self.df = self._preprocess_inventory(inventory_df)
        self.weather = weather_data if weather_data else {} # Handle None weather
        self.user_query = user_query
        self.client = client
        self.trend_context = self._get_trend_context()

    def _get_trend_context(self):
         current_year = datetime.datetime.now().year
         # Trend context string... (same as before)
         return f"Key Fashion Trends ({current_year}):\n- Colors: ...\nBoston Specific Considerations:\n- Weather Adaptability: ..."

    def _preprocess_inventory(self, df):
         # Preprocessing logic (parsing JSON strings etc.) - similar to Colab version's _preprocess_inventory
         # This might already be handled by read_gsheet, ensure consistency
         df_processed = df.copy()
         # Example: Ensure 'description' is a dict
         if 'description' in df_processed.columns and isinstance(df_processed['description'].iloc[0], str):
              df_processed['description'] = df_processed['description'].apply(lambda x: json.loads(x) if isinstance(x, str) and x.startswith('{') else ({} if pd.isna(x) else x))
         # Ensure list columns are lists
         list_cols = ['color', 'weather', 'occasion']
         for col in list_cols:
              if col in df_processed.columns and isinstance(df_processed[col].iloc[0], str):
                   df_processed[col] = df_processed[col].apply(lambda x: json.loads(x) if isinstance(x, str) and x.startswith('[') else ([] if pd.isna(x) else x))
         return df_processed


    def _format_inventory_for_prompt(self):
        # Formatting logic... (same as before, but access dicts/lists directly)
        lines = []
        for _, row in self.df.iterrows():
            try:
                category = row.get('category', 'Unknown').title()
                sub_category = row.get('sub-category', '').title()
                item_type = f"{category} ({sub_category})" if sub_category else category
                # Access lists/dicts directly
                colors = row.get('color', [])
                pattern = row.get('pattern', '')
                occasions = row.get('occasion', [])
                file_name = row.get('file name', 'N/A')
                color_str = '/'.join(map(str, colors)).title() if colors else 'N/A'
                pattern_str = f"({pattern.title()})" if pattern else ""
                occasion_str = ', '.join(map(str, occasions)).title() if occasions else 'Any'
                lines.append(f"- {item_type} [{file_name}]: Color(s): {color_str} {pattern_str}. Occasions: {occasion_str}")
            except Exception as e:
                st.warning(f"Skipping inventory row formatting: {e}")
                continue
        return "\n".join(lines).strip() if lines else "No inventory items available."

    # Use caching for recommendations based on inputs
    @st.cache_data(max_entries=50, ttl=3600) # Cache up to 50 recommendations for 1 hour
    def generate_recommendations(_self, style_focus='general', num_recommendations=3):
        """Generates outfit recommendations (cached)."""
        # Note: Caching requires inputs to be hashable. The DataFrame might be an issue.
        # A workaround is to pass a hash or a tuple representation, or cache at a higher level.
        # For now, assume direct caching works or handle potential issues.
        inventory_string = _self._format_inventory_for_prompt()
        if "No inventory items available." in inventory_string: return ["Error: No inventory items found."]
        # Construct prompt... (same as before)
        prompt_focus_instruction = "..." # Based on style_focus
        weather_desc = f"{_self.weather.get('temp_celsius', 'N/A')}°C..."
        output_format = """...""" # Same format
        system_prompt_recommend = f"""... (Full prompt using inventory_string, weather_desc, focus, context, format) ..."""
        try:
            response = _self.client.chat.completions.create(
                model="gpt-4o", messages=[{"role": "system", "content": system_prompt_recommend}],
                temperature=0.7, max_tokens=1500, n=1, stop=None
            )
            raw_output = response.choices[0].message.content
            return _self._parse_and_split_recommendations(raw_output, num_recommendations)
        except Exception as e:
            st.error(f"Recommendation generation failed: {e}")
            return [f"Error: Failed to get recommendations - {str(e)}"] # Return error message

    def _parse_and_split_recommendations(self, text, expected_num):
        # Parsing logic... (same as before)
        if not text: return ["Error: Empty response."]
        recommendations = re.split(r'\n\s*\n(?=.*\*\*Outfit Name:.*?\*\*)|\n\s*\n\s*\n', text.strip())
        cleaned = [rec.strip() for rec in recommendations if rec.strip() and '**Outfit Name:**' in rec]
        # Add warning/fallback if needed...
        return cleaned

    # Cache evaluation results
    @st.cache_data(max_entries=100, ttl=3600)
    def evaluate_outfit(_self, outfit_string, style_focus='general'):
        """Evaluates a single outfit (cached)."""
        if not _self.client: return {"error": "OpenAI client missing."}
        if not outfit_string or "Error:" in outfit_string: return {"error": "Invalid outfit input."}
        # Construct evaluation prompt... (same as before)
        evaluation_prompt = f"""... (Full prompt using user_query, style_focus, weather, outfit_string, trend_context) ..."""
        try:
            response = _self.client.chat.completions.create(
                model="gpt-4o", messages=[{"role": "system", "content": evaluation_prompt}],
                temperature=0.3, max_tokens=600, response_format={"type": "json_object"}
            )
            evaluation_json_str = response.choices[0].message.content
            evaluation_data = json.loads(evaluation_json_str)
            # Validation... (same as before)
            required_keys = ["query_suitability", ...]
            if not all(key in evaluation_data... for key in required_keys):
                 raise ValueError("Invalid evaluation structure.")
            return evaluation_data
        except Exception as e:
            st.error(f"Outfit evaluation failed: {e}")
            return {"error": f"Evaluation Error: {str(e)}"}


# --- Agent: Image Generation (Adapted) ---
def format_outfit_to_sentence(structured_output):
    # Formatting logic... (same as before)
    items = []
    try:
        lines = structured_output.strip().split('\n')
        for line in lines:
            if line.startswith(("Top:", "Bottom:", "Outerwear:", "Shoes:", "Accessories:")):
                 parts = line.split(' - ')[0]
                 item_desc = parts.split(':', 1)[1].strip()
                 if item_desc and "Not Available" not in item_desc: items.append(item_desc.lower())
        if not items: return "a person in a standard outfit"
        if len(items) == 1: return f"a person wearing {items[0]}"
        if len(items) == 2: return f"a person wearing {items[0]} and {items[1]}"
        return f"a person wearing {', '.join(items[:-1])}, and {items[-1]}"
    except Exception: return "a person in a stylish outfit"

# Cache generated image URLs based on the prompt details
@st.cache_data(max_entries=100, ttl=86400) # Cache images for a day
def generate_outfit_image_cached(outfit_recommendation_text, skin_tone, gender):
     """Generates outfit image (cached)."""
     if not client: return None
     if not outfit_recommendation_text or "Error:" in outfit_recommendation_text: return None

     formatted_sentence = format_outfit_to_sentence(outfit_recommendation_text)
     final_prompt = f"Create an ultra-realistic, full-body cinematic studio portrait of a single stylish {gender}..." # Full prompt

     try:
         response = client.images.generate(
             model="dall-e-3", prompt=final_prompt, size="1024x1024",
             quality="standard", n=1, response_format="url"
         )
         image_url = response.data[0].url
         return image_url
     except Exception as e:
         st.error(f"Image generation failed: {e}")
         return None