# -*- coding: utf-8 -*-
"""pages/2_My_Closet_&_Chat

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OHAcNZCnl1WZNc0NqNS3EFzEZBhCqByh
"""

# pages/2_👗_My_Closet_&_Chat.py
import streamlit as st
import pandas as pd
import json
from backend import (
    read_gsheet, CATALOG_FOLDER_ID, WeatherAgent, OPENWEATHER_API_KEY,
    is_query_relevant, FashionRecommender, generate_outfit_image_cached
)
from auth import get_gspread_client, get_drive_service, credentials_from_dict

st.set_page_config(page_title="Closet & Chat - Wardrobe Wizard", page_icon="")

st.markdown("# My Closet & Chat ")

# --- Authentication Check ---
if not st.session_state.get('authenticated', False):
    st.warning("Please connect your Google Account on the Introduction page first.")
    st.stop()
if not st.session_state.get('gender'):
     st.warning("Please select your wardrobe gender on the Introduction page.")
     st.stop()

# --- Initialize API Clients ---
creds_dict = st.session_state.get('google_credentials')
gc = get_gspread_client(creds_dict) # Uses cached client
drive_service = get_drive_service(creds_dict) # Uses cached client

if not gc or not drive_service:
    st.error("Failed to initialize Google services. Cannot load inventory.")
    st.stop()

# --- Load Inventory ---
sheet_name = f"Inventory_List_{st.session_state['gender'].capitalize()}s"
with st.spinner(f"Loading inventory from '{sheet_name}'..."):
    inventory_df = read_gsheet(gc, drive_service, CATALOG_FOLDER_ID, sheet_name) # Uses cached data

if inventory_df is None:
    st.error(f"Could not load inventory sheet '{sheet_name}'. Please ensure it exists or upload items on the Introduction page.")
    st.stop()
elif inventory_df.empty:
     st.warning(f"Your inventory sheet '{sheet_name}' is empty. Please upload items on the Introduction page.")
     # Don't stop, allow chat but recommender might fail

st.session_state['inventory_df'] = inventory_df # Store in session state if needed by recommender

# --- Display Inventory Section ---
with st.expander("View My Closet Items", expanded=False):
    if not inventory_df.empty:
        st.write(f"Found {len(inventory_df)} items.")
        # Display images (simplified - needs improvement for many items)
        # TODO: Implement pagination or better display for large inventories
        # TODO: Fetch actual images using Drive API or use thumbnail links
        num_cols = 5 # Number of columns for images
        cols = st.columns(num_cols)
        for i, row in inventory_df.head(15).iterrows(): # Show first 15 items for now
            col_index = i % num_cols
            # Placeholder for image display - replace with actual image fetching/display
            with cols[col_index]:
                 st.caption(row.get('file name', 'Unknown File'))
                 # Try using thumbnail link if available
                 thumb_link = row.get('thumbnailLink') # Assuming this column might exist if get_files_in_drive_folder is adapted
                 if thumb_link:
                      st.image(thumb_link, width=100)
                 else:
                      st.image("https://placehold.co/100x100/eee/ccc?text=NoThumb", width=100) # Placeholder
                 with st.popover("Details"):
                      st.write(f"**Category:** {row.get('category', 'N/A')}")
                      st.write(f"**Sub-Cat:** {row.get('sub-category', 'N/A')}")
                      # Display lists nicely
                      st.write(f"**Color:** {', '.join(row.get('color', [])) if row.get('color') else 'N/A'}")
                      st.write(f"**Pattern:** {row.get('pattern', 'N/A')}")
                      st.write(f"**Weather:** {', '.join(row.get('weather', [])) if row.get('weather') else 'N/A'}")
                      st.write(f"**Occasion:** {', '.join(row.get('occasion', [])) if row.get('occasion') else 'N/A'}")

    else:
        st.write("Your closet is empty.")

st.divider()

# --- Chatbot Interface ---
st.subheader(" Fashion Chat")

# --- User Inputs for Chat (Zip Code, Skin Tone, Style Focus) ---
col1, col2, col3 = st.columns(3)
with col1:
    st.session_state['zip_code'] = st.text_input("Your Boston Zip Code:", st.session_state.get('zip_code', "02116"))
with col2:
    st.session_state['skin_tone'] = st.text_input("Your Skin Tone (for image gen):", st.session_state.get('skin_tone', "neutral"))
with col3:
    style_focus = st.selectbox(
        "Recommendation Style Focus:",
        ('general', 'trendy', 'boston_trendy'),
        index=2, # Default to boston_trendy
        key='style_focus_select'
    )


# --- Display Chat History ---
if 'chat_history' not in st.session_state:
    st.session_state.chat_history = []

for message in st.session_state.chat_history:
    with st.chat_message(message["role"]):
        # Handle different content types in the message
        if "text" in message:
            st.markdown(message["text"])
        if "evaluation" in message:
            eval_data = message["evaluation"]
            if eval_data and "error" not in eval_data:
                 score = eval_data.get('overall_score', {}).get('score', 0)
                 justification = eval_data.get('overall_score', {}).get('justification', 'N/A')
                 st.markdown(f"**Overall Score:** {'★'*score}{'☆'*(5-score)} ({score}/5)")
                 with st.expander("View Evaluation Details"):
                      st.json(eval_data) # Display full evaluation JSON
            elif eval_data:
                 st.warning(f"Evaluation failed: {eval_data['error']}")
        if "image_url" in message:
            if message["image_url"]:
                st.image(message["image_url"], caption="AI Generated Outfit Visualization")
            else:
                st.warning("Image generation failed or was skipped.")
        if "save_key" in message: # Button to save outfit
             if st.button(" Save Outfit", key=message["save_key"]):
                  # Find the corresponding recommendation data to save
                  # This requires structuring chat history better or passing data
                  # For simplicity, let's assume we save the text for now
                  # A better approach would store the full recommendation object
                  outfit_to_save = {"recommendation": message.get("recommendation_text", "Error saving"),
                                    "image_url": message.get("image_url_to_save"),
                                    "evaluation": message.get("evaluation_to_save")}
                  st.session_state.saved_outfits.append(outfit_to_save)
                  st.success("Outfit saved!")
                  # Disable button after click? Not straightforward in Streamlit loops
                  # Consider removing the button or showing "Saved" status


# --- Chat Input ---
if prompt := st.chat_input("What outfit are you looking for?"):
    # Add user message to chat history
    st.session_state.chat_history.append({"role": "user", "text": prompt})
    # Display user message immediately
    with st.chat_message("user"):
        st.markdown(prompt)

    # --- Backend Processing ---
    with st.chat_message("assistant"):
        message_placeholder = st.empty() # Placeholder for streaming/spinner
        full_response = ""

        with st.spinner("Thinking..."):
            # 1. Check Relevancy
            if not is_query_relevant(prompt):
                full_response = "My apologies, I can only help with fashion and outfit suggestions. How else can I assist with your wardrobe?"
                message_placeholder.markdown(full_response)
                st.session_state.chat_history.append({"role": "assistant", "text": full_response})
                st.stop() # Stop processing if irrelevant

            # 2. Get Weather
            weather_data = None
            if st.session_state['zip_code'] and OPENWEATHER_API_KEY:
                 try:
                      weather_agent = WeatherAgent(zip_code=st.session_state['zip_code'], api_key=OPENWEATHER_API_KEY)
                      weather_data = weather_agent.get_weather(weather_agent) # Pass instance for caching workaround
                      st.write(f"_Weather in {st.session_state['zip_code']}: {weather_data['description']}, {weather_data['temp_celsius']}°C_")
                 except Exception as e:
                      st.warning(f"Could not fetch weather: {e}")
            else:
                 st.warning("Zip code or Weather API key missing, proceeding without weather data.")


            # 3. Generate Recommendations
            recommendations = []
            if inventory_df is not None and not inventory_df.empty:
                 try:
                      recommender = FashionRecommender(
                           inventory_df=inventory_df,
                           weather_data=weather_data,
                           user_query=prompt
                      )
                      # Pass the instance itself for caching to work with the method
                      recommendations = recommender.generate_recommendations(recommender, style_focus=style_focus)
                 except Exception as e:
                      st.error(f"Failed to generate recommendations: {e}")
                      recommendations = [f"Error: Could not generate recommendations. {e}"]
            else:
                 recommendations = ["Error: Inventory is empty or could not be loaded."]


            # --- Process and Display Each Recommendation ---
            assistant_responses = [] # Store parts of the response for history
            for i, rec_text in enumerate(recommendations):
                 if "Error:" in rec_text:
                      st.error(rec_text)
                      assistant_responses.append({"role": "assistant", "text": rec_text})
                      continue # Skip evaluation/image gen if recommendation failed

                 st.markdown(f"**Recommendation {i+1}:**")
                 st.markdown(rec_text) # Display recommendation text

                 current_rec_response = {"role": "assistant", "text": f"**Recommendation {i+1}:**\n{rec_text}"}


                 # 4. Evaluate Outfit
                 evaluation = None
                 if 'recommender' in locals():
                      with st.spinner(f"Evaluating recommendation {i+1}..."):
                           evaluation = recommender.evaluate_outfit(recommender, rec_text, style_focus=style_focus)
                      if evaluation and "error" not in evaluation:
                           score = evaluation.get('overall_score', {}).get('score', 0)
                           st.markdown(f"**Overall Score:** {'★'*score}{'☆'*(5-score)} ({score}/5)")
                           # Add expander in the main display area, not history directly
                           with st.expander("View Evaluation Details"):
                                st.json(evaluation)
                           current_rec_response["evaluation"] = evaluation # Add eval to history item
                      elif evaluation:
                           st.warning(f"Evaluation failed: {evaluation['error']}")
                           current_rec_response["evaluation"] = evaluation # Store error in history
                      else:
                           st.warning("Evaluation returned None.")


                 # 5. Generate Image
                 image_url = None
                 with st.spinner(f"Generating image for recommendation {i+1}..."):
                      image_url = generate_outfit_image_cached(
                           rec_text, # Use text as part of cache key
                           st.session_state['skin_tone'],
                           st.session_state['gender']
                      )
                 if image_url:
                      st.image(image_url, caption="AI Generated Outfit Visualization")
                      current_rec_response["image_url"] = image_url # Add image url to history item
                 else:
                      st.warning("Image generation failed.")


                 # Add save button data - generate unique key
                 save_key = f"save_{len(st.session_state.chat_history)}_{i}"
                 current_rec_response["save_key"] = save_key
                 # Add data needed for saving
                 current_rec_response["recommendation_text"] = rec_text
                 current_rec_response["image_url_to_save"] = image_url
                 current_rec_response["evaluation_to_save"] = evaluation

                 # Add button here - this button appears with the assistant message
                 if st.button(" Save Outfit", key=save_key):
                      outfit_to_save = {"recommendation": rec_text,
                                        "image_url": image_url,
                                        "evaluation": evaluation}
                      st.session_state.saved_outfits.append(outfit_to_save)
                      st.success(f"Outfit {i+1} saved!")
                      # Rerun might be needed to reflect saved state immediately
                      # st.rerun()

                 st.divider() # Separator between recommendations

                 # Add the complete response block for this recommendation to history
                 st.session_state.chat_history.append(current_rec_response)


            # Clear the initial placeholder
            message_placeholder.empty()
