# -*- coding: utf-8 -*-
"""pages/3_⭐_Saved_Outfits

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rK-mXxSnsAxdRHPbuySXsiBaXLzh4ILp
"""

# pages/3_⭐_Saved_Outfits.py
import streamlit as st
import json

st.set_page_config(page_title="Saved Outfits - Wardrobe Wizard", page_icon="⭐")

st.markdown("# ⭐ My Saved Outfits")

# --- Authentication Check ---
if not st.session_state.get('authenticated', False):
    st.warning("Please connect your Google Account on the Introduction page first.")
    st.stop()

# --- Load Saved Outfits ---
if 'saved_outfits' not in st.session_state or not st.session_state.saved_outfits:
    st.info("You haven't saved any outfits yet. Save your favorites from the Chat page!")
    st.stop()

saved_outfits = st.session_state.saved_outfits
st.write(f"You have {len(saved_outfits)} saved outfits.")
st.divider()

# --- Display Saved Outfits ---
for i, outfit in enumerate(saved_outfits):
    with st.container(border=True):
        col1, col2 = st.columns([2, 1]) # Text on left, image/score on right

        with col1:
            st.subheader(f"Saved Outfit {i+1}")
            # Display recommendation text
            st.markdown(outfit.get("recommendation", "Recommendation text not found."))

        with col2:
            # Display image if available
            img_url = outfit.get("image_url")
            if img_url:
                st.image(img_url, caption="Generated Visualization")
            else:
                st.caption("No image available.")

            # Display score if available
            evaluation = outfit.get("evaluation")
            if evaluation and isinstance(evaluation, dict) and "error" not in evaluation:
                 score = evaluation.get('overall_score', {}).get('score', 0)
                 st.markdown(f"**Overall Score:** {'★'*score}{'☆'*(5-score)} ({score}/5)")
                 with st.expander("View Evaluation Details"):
                      st.json(evaluation)
            elif evaluation and isinstance(evaluation, dict) and "error" in evaluation:
                 st.warning(f"Evaluation Error: {evaluation['error']}")
            else:
                 st.caption("No evaluation score available.")

        # Add a button to remove the saved outfit (optional)
        if st.button(f"Remove Outfit {i+1}", key=f"remove_{i}"):
             st.session_state.saved_outfits.pop(i) # Remove item from list by index
             st.rerun() # Rerun to update the display

    st.divider()