# -*- coding: utf-8 -*-
"""pages/1_Introduction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipljXgOAPaMfXsj92QSJoA3ZOBla1O_Y
"""

# pages/1_👋_Introduction.py
import streamlit as st
from auth import get_auth_url, get_gspread_client, get_drive_service, credentials_from_dict
from backend import process_uploaded_files, update_gsheet, create_gsheet, read_gsheet, CATALOG_FOLDER_ID
import pandas as pd
import time

st.set_page_config(page_title="Introduction - Wardrobe Wizard", page_icon="")

st.markdown("# Welcome to Wardrobe Wizard! ")
st.write("""
Wardrobe Wizard is your personal AI fashion assistant. Catalog your closet, get personalized outfit recommendations based on your items and current weather, visualize the looks, and save your favorites!

**Features:**
* **Connect Google Drive:** Securely link your Google Drive to automatically manage your clothing inventory stored in Google Sheets.
* **Upload Clothes:** Easily upload images of your clothing items to build your digital wardrobe.
* **AI Analysis:** Our AI analyzes your clothing items to understand their type, color, style, and suitable occasions/weather.
* **Smart Recommendations:** Get outfit suggestions tailored to your inventory, the weather (in Boston, MA), and your requests (e.g., "casual brunch outfit", "trendy night out").
* **Visualize Outfits:** See AI-generated images of the recommended outfits.
* **Evaluate & Save:** Get AI-powered evaluations of suggested outfits and save the ones you love.

**Get Started:** Connect your Google Account below to begin!
""")
st.divider()

# --- Authentication ---
if not st.session_state.get('authenticated', False):
    st.subheader("Connect Your Google Account")
    st.write("We need access to Google Drive and Sheets to manage your wardrobe inventory.")
    auth_url = get_auth_url()
    # Use st.link_button for a cleaner look
    st.link_button("Connect Google Drive", auth_url, type="primary")
    st.caption("You will be redirected to Google to authorize access.")
else:
    st.success(f"Connected as {st.session_state.get('user_info', {}).get('email', 'User')}")
    st.subheader("Initial Setup")

    # --- Gender Selection ---
    if 'gender' not in st.session_state or st.session_state['gender'] is None:
         st.session_state['gender'] = st.radio(
              "Select your primary wardrobe type:",
              ("women", "men"),
              horizontal=True,
              key="gender_select"
         )
         st.button("Confirm Gender") # Button to lock gender choice for the session


    if st.session_state.get('gender'):
         st.write(f"Operating on **{st.session_state['gender'].capitalize()}**'s wardrobe.")

         # --- Initialize API Clients (only if authenticated) ---
         creds_dict = st.session_state.get('google_credentials')
         creds = credentials_from_dict(creds_dict)
         gc = get_gspread_client(creds_dict) # Will use cached client
         drive_service = get_drive_service(creds_dict) # Will use cached client

         if not gc or not drive_service:
              st.error("Failed to initialize Google services. Please check credentials or permissions.")
         else:
              # --- File Uploader ---
              st.subheader("Upload Initial Clothing Images")
              st.write("Upload images of your clothes to start building your inventory. This will be processed and stored in a Google Sheet in your Drive.")

              uploaded_files = st.file_uploader(
                   "Choose image files (.jpg, .png, .webp)",
                   accept_multiple_files=True,
                   type=["jpg", "jpeg", "png", "webp"]
              )

              if uploaded_files:
                   if st.button("Process Uploaded Files", type="primary"):
                        with st.spinner("Analyzing images and updating inventory... This may take a while."):
                             # Process uploaded files
                             new_inventory_df = process_uploaded_files(uploaded_files)

                             if not new_inventory_df.empty:
                                  st.write(f"Successfully analyzed {len(new_inventory_df)} items.")
                                  # Determine sheet name based on gender
                                  sheet_name = f"Inventory_List_{st.session_state['gender'].capitalize()}s"
                                  # Try to update or create the sheet
                                  existing_df = read_gsheet(gc, drive_service, CATALOG_FOLDER_ID, sheet_name)

                                  success = False
                                  if existing_df is not None: # Sheet exists or read attempt was made
                                       st.write(f"Updating existing sheet: {sheet_name}")
                                       success = update_gsheet(gc, drive_service, CATALOG_FOLDER_ID, sheet_name, new_inventory_df)
                                  else: # Sheet likely doesn't exist
                                       st.write(f"Creating new sheet: {sheet_name}")
                                       success = create_gsheet(gc, drive_service, CATALOG_FOLDER_ID, sheet_name, new_inventory_df)

                                  if success:
                                       st.success("Inventory updated successfully in Google Sheets!")
                                       # Optionally clear uploader or show success message
                                  else:
                                       st.error("Failed to update inventory in Google Sheets.")
                             else:
                                  st.warning("No valid clothing items were processed from the uploaded files.")

              st.divider()
              st.write("Once you have uploaded initial items (or if your inventory sheet already exists), proceed to the Closet & Chat page.")
              if st.button("Go to My Closet & Chat ->"):
                   st.switch_page("pages/2_👗_My_Closet_&_Chat.py")

    else:
         st.warning("Please select your wardrobe type (Men/Women) to proceed.")
