# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kqhWudrJUStcJg7GgSF1innvKLmC3kF
"""

# streamlit_app.py
import streamlit as st
# Import necessary functions from your auth module
# Make sure auth.py is in the same directory or accessible
from auth import get_auth_url, exchange_code_for_credentials, credentials_from_dict, get_user_info
import time

# --- Page Configuration (Should be the first Streamlit command) ---
st.set_page_config(
    page_title="Wardrobe Wizard",
    page_icon="🪄",
    layout="wide", # Use wide layout for more space
    initial_sidebar_state="expanded" # Keep sidebar open initially
)

# --- Initialize Session State ---
# Use a dictionary for defaults to make it cleaner
default_session_state = {
    'google_credentials': None,
    'user_info': None,
    'authenticated': False,
    'inventory_df': None,
    'chat_history': [],
    'saved_outfits': [],
    'current_recommendations': [],
    'gender': None, # Store user's selected gender
    'zip_code': None, # Store user's zip code
    'skin_tone': 'neutral' # Default skin tone
}
# Initialize only if keys don't exist
for key, default_value in default_session_state.items():
    if key not in st.session_state:
        st.session_state[key] = default_value

# --- Authentication Check & Handling Callback ---
# This logic runs on every page load to handle the OAuth callback
query_params = st.query_params
# Check if 'code' and 'state' are in query params and user is not already authenticated
if "code" in query_params and "state" in query_params and not st.session_state.get('authenticated', False):
    code = query_params.get("code")
    state = query_params.get("state")
    # Attempt to exchange code for credentials only once
    if code and state: # Ensure they are not empty
        with st.spinner("Authenticating with Google..."):
            creds = exchange_code_for_credentials(code, state)
            if creds:
                st.session_state['authenticated'] = True
                user_info = get_user_info(creds) # Fetch and store user info
                st.success(f"Successfully authenticated as {st.session_state.get('user_info', {}).get('name', 'User')}!")
                # Clear query params after successful auth to prevent re-triggering
                st.query_params.clear()
                time.sleep(2) # Give time for user to see success message
                st.rerun() # Rerun to update the UI state reflecting authentication
            else:
                st.error("Authentication failed during token exchange.")
                # Clear potentially bad state
                st.session_state['authenticated'] = False
                st.session_state['google_credentials'] = None
                st.query_params.clear() # Clear params even on failure

# --- App Header (Appears on all pages) ---
st.title("🪄 Wardrobe Wizard")
st.caption("Your AI-Powered Fashion Assistant")

# --- Display User Info if Authenticated (Appears on all pages) ---
if st.session_state.get('authenticated', False) and st.session_state.get('user_info'):
    user = st.session_state['user_info']
    # Use columns for better layout
    col1, col2 = st.columns([0.15, 0.85], gap="small") # Adjust column ratios
    with col1:
        st.image(user.get('picture', ''), width=70, use_column_width=False) # Control image width
    with col2:
        st.subheader(f"Welcome, {user.get('given_name', 'User')}!")
        st.write(f"Logged in as: {user.get('email', 'N/A')}")
    st.divider() # Visual separator
elif "code" not in query_params: # Don't show this during the auth callback phase
     st.info("Please go to the Introduction page to connect your Google Account.")


# --- Sidebar Navigation Hint ---
# Streamlit automatically creates navigation from files in the 'pages/' directory
st.sidebar.header("Navigation")
st.sidebar.info("Select a page above to get started.")
st.sidebar.page_link("streamlit_app.py", label="Home (This Page)", icon="🏠")
st.sidebar.page_link("pages/1_👋_Introduction.py", label="Introduction & Setup", icon="👋")
st.sidebar.page_link("pages/2_👗_My_Closet_&_Chat.py", label="Closet & Chat", icon="👗")
st.sidebar.page_link("pages/3_⭐_Saved_Outfits.py", label="Saved Outfits", icon="⭐")


# --- Logout Button in Sidebar ---
if st.session_state.get('authenticated', False):
    st.sidebar.divider()
    if st.sidebar.button("Logout", type="secondary"):
        # Clear session state related to auth and user data
        keys_to_clear = ['google_credentials', 'user_info', 'authenticated',
                         'chat_history', 'saved_outfits', 'inventory_df', 'gender', 'zip_code']
        for key in keys_to_clear:
            if key in st.session_state:
                del st.session_state[key] # Or set to None if preferred
        st.success("Logged out successfully.")
        time.sleep(1)
        st.rerun() # Rerun to reflect logged-out state

# --- Main App Logic ---
# This main script usually just sets up the global elements.
# The actual content for each page is defined in the files within the 'pages/' directory.
st.markdown("---") # Footer separator
st.caption("Select a page from the sidebar to continue.")